class HomeController < ApplicationController
  def hello
    setupFile = 'ddddddddddsfdsfsdfsfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd'
  end
end
